### ISSUE TITLE
Can i run on windows?

### ISSUE THREAD

**Issue by talhaanwarch** [marella/ctransformers#76]
I tried to run on windows and i get this error
```
ERROR:    Traceback (most recent call last):
  File "C:\streamlit-llama\venv\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\streamlit-llama\venv\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\streamlit-llama\venv\lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\streamlit-llama\api.py", line 22, in startup_event
    app.state.model = load_model()
  File "C:\streamlit-llama\api.py", line 15, in load_model
    return AutoModelForCausalLM.from_pretrained(
  File "C:\streamlit-llama\venv\lib\site-packages\ctransformers\hub.py", line 168, in from_pretrained
    return LLM(
  File "C:\streamlit-llama\venv\lib\site-packages\ctransformers\llm.py", line 206, in __init__
    self._lib = load_library(lib, cuda=config.gpu_layers > 0)
  File "C:\streamlit-llama\venv\lib\site-packages\ctransformers\llm.py", line 102, in load_library
    lib = CDLL(path)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\streamlit-llama\venv\Lib\site-packages\ctransformers\lib\avx2\ctransformers.dll' (or one of its dependencies). Try using the full path with constructor syntax.

ERROR:    Application startup failed. Exiting.
```
Windows 11

**Comment by bbartling** [comment]
Windows 10 and python 3.10 is working for me just fine.

**Comment by talhaanwarch** [comment]
are you using conda ?

**Comment by bbartling** [comment]
No not using Conda. Just ordinary or "vanilla" python.

```
> py -3.10
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

I most likely just installed the .exe executable from and added PATH during the installation:

- https://www.python.org/downloads/release/python-3106/

I think this one:
`<html>
<body>


Windows installer (64-bit) | Windows | Recommended | 8f46453e68ef38e5544a76d84df3994c | 28916488 | SIG
-- | -- | -- | -- | -- | --



</body>
</html>[Windows installer (64-bit)](https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe)	Windows	Recommended	8f46453e68ef38e5544a76d84df3994c	28916488	[SIG](https://www.python.org/ftp/python/3.10.6/python-3.10.6-amd64.exe.asc)`

**Comment by andreapagliacci** [comment]
I have the same issue in Mac OS X, with python 3.10, ctransformers 0.2.2.4 (the last) using Conda
