### ISSUE TITLE
TypeError of loading a local GPTQ model 

### ISSUE THREAD

**Issue by jameschung2000** [marella/ctransformers#79]
Try to load a local GPTQ model, and get the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/temp/test.py", line 3, in <module>
    llm = AutoModelForCausalLM.from_pretrained('/disk1/projects/jameszhong/text-generation-webui/models/llama-2-13B-Guanaco-QLoRA-GPTQ')
  File "/home/ubuntu/anaconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/hub.py", line 135, in from_pretrained
    return gptq.AutoModelForCausalLM.from_pretrained(
  File "/home/ubuntu/anaconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/gptq/hub.py", line 66, in from_pretrained
    return LLM(model_path=model_path, config=config)
  File "/home/ubuntu/anaconda3/envs/textgen/lib/python3.10/site-packages/ctransformers/gptq/llm.py", line 51, in __init__
    raise ValueError(f"No model file found in directory '{model_path}'")
ValueError: No model file found in directory '/disk1/projects/jameszhong/text-generation-webui/models'
```
In `ctransformers/gptq/llm.py`  line 56-58:

```
        model_path = None
        if path_type == "file":
            model_path = Path(model_path).parent
```

For a local model, the `model_path` variable is `None`, then the parameter for function Path should be `model_path_or_repo_id`.  Also, if the user just supplies a model directory, the `path_type` is `dir`, which is not included in the logic. Suggest the code should be changed to the following:

```
        if path_type == "file" :
            model_path = Path(model_path_or_repo_id).parent
        elif path_type == "dir" :
            model_path = Path(model_path_or_repo_id)
```

**Comment by jameschung2000** [comment]
Fixed
